language: node_js
dist: xenial
node_js:
    - 'lts/*'
branches:
    only:
        - master
script:
    - npx create-apex-js-app testApp -s -t git+https://git@github.com/dfrechdev/apexjs-template-js-lib.git && cd testApp && npm run build

